[package]
name = "wasm"
version = "0.1.0"
authors = ["LeahPeach"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.83"

[dependencies.web-sys]
version = "0.3.60"
features = [ 
    "Window", 
    "console"
] 
