/***
 * These are all the base objects of our hexii. Literally, they're the data that matches the images used in the hexagons.
 *
 * Of note, hexagon edgelines are laid out like this:
 *
 *              1       2
 *
 *          6      hex       3
 *
 *              5       4
 */

let hexii = [
    {
        name: "ph_1",
        src: "project/src/hexgen/heximg/ph_1.png",
        version: 0,
        edgelines: {
            default: ["forest", "forest", "plains", "lake", "lake", "road"],
            rOnce: ["road", "forest", "forest", "plains", "lake", "lake"],
            rTwice: ["lake", "road", "forest", "forest", "plains", "lake"],
            rThrice: ["lake", "lake", "road", "forest", "forest", "plains"],
            rQuarce: ["plains", "lake", "lake", "road", "forest", "forest"],
            rQuince: ["forest", "plains", "lake", "lake", "road", "forest"],
            inverted: ["forest", "forest", "road", "lake", "lake", "plains"],
            irOnce: ["plains", "forest", "forest", "road", "lake", "lake"],
            irTwice: ["lake", "plains", "forest", "forest", "road", "lake"],
            irThrice: ["lake", "lake", "plains", "forest", "forest", "road"],
            irQuarce: ["road", "lake", "lake", "plains", "forest", "forest"],
            irQuince: ["forest", "road", "lake", "lake", "plains", "forest"],
        },
    },
    {
        name: "ph_2",
        src: "project/src/hexgen/heximg/ph_2.png",
        version: 0,
        edgelines: {
            default: ["lake", "forest", "plains", "plains", "plains", "plains"],
            rOnce: ["plains", "lake", "forest", "plains", "plains", "plains"],
            rTwice: ["plains", "plains", "lake", "forest", "plains", "plains"],
            rThrice: ["plains", "plains", "plains", "lake", "forest", "plains"],
            rQuarce: ["plains", "plains", "plains", "plains", "lake", "forest"],
            rQuince: ["forest", "plains", "plains", "plains", "plains", "lake"],
            inverted: ["forest", "lake", "plains", "plains", "plains", "plains"],
            irOnce: ["plains", "forest", "lake", "plains", "plains", "plains"],
            irTwice: ["plains", "plains", "forest", "lake", "plains", "plains"],
            irThrice: ["plains", "plains", "plains", "forest", "lake", "plains"],
            irQuarce: ["plains", "plains", "plains", "plains", "forest", "lake"],
            irQuince: ["lake", "plains", "plains", "plains", "plains", "forest"],
        },
    },
    {
        name: "ph_3",
        src: "project/src/hexgen/heximg/ph_3.png",
        version: 0,
        edgelines: {
            default: ["plains", "forest", "plains", "plains", "plains", "forest"],
            rOnce: ["forest", "plains", "forest", "plains", "plains", "plains"],
            rTwice: ["plains", "forest", "plains", "forest", "plains", "plains"],
            rThrice: ["plains", "plains", "forest", "plains", "forest", "plains"],
            rQuarce: ["plains", "plains", "plains", "forest", "plains", "forest"],
            rQuince: ["forest", "plains", "plains", "plains", "forest", "plains"],
            inverted: ["forest", "plains", "forest", "plains", "plains", "plains"],
            irOnce: ["plains", "forest", "plains", "forest", "plains", "plains"],
            irTwice: ["plains", "plains", "forest", "plains", "forest", "plains"],
            irThrice: ["plains", "plains", "plains", "forest", "plains", "forest"],
            irQuarce: ["forest", "plains", "plains", "plains", "forest", "plains"],
            irQuince: ["plains", "forest", "plains", "plains", "plains", "forest"],
        },
    },
    {
        name: "ph_4",
        src: "project/src/hexgen/heximg/ph_4.png",
        version: 0,
        edgelines: {
            default: ["lake", "forest", "plains", "plains", "plains", "forest"],
            rOnce: ["forest", "lake", "forest", "plains", "plains", "plains"],
            rTwice: ["plains", "forest", "lake", "forest", "plains", "plains"],
            rThrice: ["plains", "plains", "forest", "lake", "forest", "plains"],
            rQuarce: ["plains", "plains", "plains", "forest", "lake", "forest"],
            rQuince: ["forest", "plains", "plains", "plains", "forest", "lake"],
            inverted: ["forest", "lake", "forest", "plains", "plains", "plains"],
            irOnce: ["plains", "forest", "lake", "forest", "plains", "plains"],
            irTwice: ["plains", "plains", "forest", "lake", "forest", "plains"],
            irThrice: ["plains", "plains", "plains", "forest", "lake", "forest"],
            irQuarce: ["forest", "plains", "plains", "plains", "forest", "lake"],
            irQuince: ["lake", "forest", "plains", "plains", "plains", "forest"],
        },
    },
    {
        name: "ph_5",
        src: "project/src/hexgen/heximg/ph_5.png",
        version: 0,
        edgelines: {
            default: ["forest", "forest", "plains", "plains", "plains", "lake"],
            rOnce: ["lake", "forest", "forest", "plains", "plains", "plains"],
            rTwice: ["plains", "lake", "forest", "forest", "plains", "plains"],
            rThrice: ["plains", "plains", "lake", "forest", "forest", "plains"],
            rQuarce: ["plains", "plains", "plains", "lake", "forest", "forest"],
            rQuince: ["forest", "plains", "plains", "plains", "lake", "forest"],
            inverted: ["forest", "forest", "lake", "plains", "plains", "plains"],
            irOnce: ["plains", "forest", "forest", "lake", "plains", "plains"],
            irTwice: ["plains", "plains", "forest", "forest", "lake", "plains"],
            irThrice: ["plains", "plains", "plains", "forest", "forest", "lake"],
            irQuarce: ["lake", "plains", "plains", "plains", "forest", "forest"],
            irQuince: ["forest", "lake", "plains", "plains", "plains", "forest"],
        },
    },
    {
        name: "ph_6",
        src: "project/src/hexgen/heximg/ph_6.png",
        version: 0,
        edgelines: {
            default: ["road", "forest", "plains", "plains", "plains", "plains"],
            rOnce: ["plains", "road", "forest", "plains", "plains", "plains"],
            rTwice: ["plains", "plains", "road", "forest", "plains", "plains"],
            rThrice: ["plains", "plains", "plains", "road", "forest", "plains"],
            rQuarce: ["plains", "plains", "plains", "plains", "road", "forest"],
            rQuince: ["forest", "plains", "plains", "plains", "plains", "road"],
            inverted: ["forest", "road", "plains", "plains", "plains", "plains"],
            irOnce: ["plains", "forest", "road", "plains", "plains", "plains"],
            irTwice: ["plains", "plains", "forest", "road", "plains", "plains"],
            irThrice: ["plains", "plains", "plains", "forest", "road", "plains"],
            irQuarce: ["plains", "plains", "plains", "plains", "forest", "road"],
            irQuince: ["road", "plains", "plains", "plains", "plains", "forest"],
        },
    },
    {
        name: "ph_7",
        src: "project/src/hexgen/heximg/ph_7.png",
        version: 0,
        edgelines: {
            default: ["road", "lake", "plains", "plains", "plains", "plains"],
            rOnce: ["plains", "road", "lake", "plains", "plains", "plains"],
            rTwice: ["plains", "plains", "road", "lake", "plains", "plains"],
            rThrice: ["plains", "plains", "plains", "road", "lake", "plains"],
            rQuarce: ["plains", "plains", "plains", "plains", "road", "lake"],
            rQuince: ["lake", "plains", "plains", "plains", "plains", "road"],
            inverted: ["lake", "road", "plains", "plains", "plains", "plains"],
            irOnce: ["plains", "lake", "road", "plains", "plains", "plains"],
            irTwice: ["plains", "plains", "lake", "road", "plains", "plains"],
            irThrice: ["plains", "plains", "plains", "lake", "road", "plains"],
            irQuarce: ["plains", "plains", "plains", "plains", "lake", "road"],
            irQuince: ["road", "plains", "plains", "plains", "plains", "lake"],
        },
    },
    {
        name: "ph_8",
        src: "project/src/hexgen/heximg/ph_8.png",
        version: 0,
        edgelines: {
            default: ["lake", "forest", "plains", "plains", "plains", "road"],
            rOnce: ["road", "lake", "forest", "plains", "plains", "plains"],
            rTwice: ["plains", "road", "lake", "forest", "plains", "plains"],
            rThrice: ["plains", "plains", "road", "lake", "forest", "plains"],
            rQuarce: ["plains", "plains", "plains", "road", "lake", "forest"],
            rQuince: ["forest", "plains", "plains", "plains", "road", "lake"],
            inverted: ["forest", "lake", "road", "plains", "plains", "plains"],
            irOnce: ["plains", "forest", "lake", "road", "plains", "plains"],
            irTwice: ["plains", "plains", "forest", "lake", "road", "plains"],
            irThrice: ["plains", "plains", "plains", "forest", "lake", "road"],
            irQuarce: ["road", "plains", "plains", "plains", "forest", "lake"],
            irQuince: ["lake", "road", "plains", "plains", "plains", "forest"],
        },
    },
    {
        name: "ph_9",
        src: "project/src/hexgen/heximg/ph_9.png",
        version: 0,
        edgelines: {
            default: ["lake", "plains", "plains", "plains", "plains", "plains"],
            rOnce: ["plains", "lake", "plains", "plains", "plains", "plains"],
            rTwice: ["plains", "plains", "lake", "plains", "plains", "plains"],
            rThrice: ["plains", "plains", "plains", "lake", "plains", "plains"],
            rQuarce: ["plains", "plains", "plains", "plains", "lake", "plains"],
            rQuince: ["plains", "plains", "plains", "plains", "plains", "lake"],
            inverted: ["plains", "lake", "plains", "plains", "plains", "plains"],
            irOnce: ["plains", "plains", "lake", "plains", "plains", "plains"],
            irTwice: ["plains", "plains", "plains", "lake", "plains", "plains"],
            irThrice: ["plains", "plains", "plains", "plains", "lake", "plains"],
            irQuarce: ["plains", "plains", "plains", "plains", "plains", "lake"],
            irQuince: ["lake", "plains", "plains", "plains", "plains", "plains"],
        },
    },
    {
        name: "ph_10",
        src: "project/src/hexgen/heximg/ph_10.png",
        version: 0,
        edgelines: {
            default: ["road", "road", "plains", "plains", "plains", "plains"],
            rOnce: ["plains", "road", "road", "plains", "plains", "plains"],
            rTwice: ["plains", "plains", "road", "road", "plains", "plains"],
            rThrice: ["plains", "plains", "plains", "road", "road", "plains"],
            rQuarce: ["plains", "plains", "plains", "plains", "road", "road"],
            rQuince: ["road", "plains", "plains", "plains", "plains", "road"],
            inverted: ["road", "road", "plains", "plains", "plains", "plains"],
            irOnce: ["plains", "road", "road", "plains", "plains", "plains"],
            irTwice: ["plains", "plains", "road", "road", "plains", "plains"],
            irThrice: ["plains", "plains", "plains", "road", "road", "plains"],
            irQuarce: ["plains", "plains", "plains", "plains", "road", "road"],
            irQuince: ["road", "plains", "plains", "plains", "plains", "road"],
        },
    },
    {
        name: "ph_11",
        src: "project/src/hexgen/heximg/ph_11.png",
        version: 0,
        edgelines: {
            default: ["road", "lake", "plains", "plains", "plains", "road"],
            rOnce: ["road", "road", "lake", "plains", "plains", "plains"],
            rTwice: ["plains", "road", "road", "lake", "plains", "plains"],
            rThrice: ["plains", "plains", "road", "road", "lake", "plains"],
            rQuarce: ["plains", "plains", "plains", "road", "road", "lake"],
            rQuince: ["lake", "plains", "plains", "plains", "road", "road"],
            inverted: ["lake", "road", "road", "plains", "plains", "plains"],
            irOnce: ["plains", "lake", "road", "road", "plains", "plains"],
            irTwice: ["plains", "plains", "lake", "road", "road", "plains"],
            irThrice: ["plains", "plains", "plains", "lake", "road", "road"],
            irQuarce: ["road", "plains", "plains", "plains", "lake", "road"],
            irQuince: ["road", "road", "plains", "plains", "plains", "lake"],
        },
    },
    {
        name: "ph_12",
        src: "project/src/hexgen/heximg/ph_12.png",
        version: 0,
        edgelines: {
            default: ["forest", "road", "plains", "plains", "plains", "lake"],
            rOnce: ["lake", "forest", "road", "plains", "plains", "plains"],
            rTwice: ["plains", "lake", "forest", "road", "plains", "plains"],
            rThrice: ["plains", "plains", "lake", "forest", "road", "plains"],
            rQuarce: ["plains", "plains", "plains", "lake", "forest", "road"],
            rQuince: ["road", "plains", "plains", "plains", "lake", "forest"],
            inverted: ["road", "forest", "lake", "plains", "plains", "plains"],
            irOnce: ["plains", "road", "forest", "lake", "plains", "plains"],
            irTwice: ["plains", "plains", "road", "forest", "lake", "plains"],
            irThrice: ["plains", "plains", "plains", "road", "forest", "lake"],
            irQuarce: ["lake", "plains", "plains", "plains", "road", "forest"],
            irQuince: ["forest", "lake", "plains", "plains", "plains", "road"],
        },
    },
    {
        name: "ph_13",
        src: "project/src/hexgen/heximg/ph_13.png",
        version: 0,
        edgelines: {
            default: ["plains", "lake", "plains", "plains", "plains", "road"],
            rOnce: ["road", "plains", "lake", "plains", "plains", "plains"],
            rTwice: ["plains", "road", "plains", "lake", "plains", "plains"],
            rThrice: ["plains", "plains", "road", "plains", "lake", "plains"],
            rQuarce: ["plains", "plains", "plains", "road", "plains", "lake"],
            rQuince: ["lake", "plains", "plains", "plains", "road", "plains"],
            inverted: ["lake", "plains", "road", "plains", "plains", "plains"],
            irOnce: ["plains", "lake", "plains", "road", "plains", "plains"],
            irTwice: ["plains", "plains", "lake", "plains", "road", "plains"],
            irThrice: ["plains", "plains", "plains", "lake", "plains", "road"],
            irQuarce: ["road", "plains", "plains", "plains", "lake", "plains"],
            irQuince: ["plains", "road", "plains", "plains", "plains", "lake"],
        },
    },
];

(function (S) {
    if (!S.hex) {
        S.hex = {};
    }

    S.hex.hexii = hexii;
})(setup);
