sugarcube-2:
  # We don't want t3lt to flag our custom macros as not existing. It gets annoying.
  
  macros:
    # Part of Maliface's A macro: https://github.com/MalifaciousGames/Mali-s-Macros/blob/main/a-macro/a-macro.md
    a:
      name: a
      container: true

    # Part of Maliface's A macro:
    but:
      name: but
      container: true
    
    # Part of Maliface's A macro:
    adel:
      name: adel
      container: true
    
    # Part of Maliface's A macro:
    butdel:
      name: butdel
      container: true

    # My custom macro for tooltips. 
    tt:
      name: tooltiptext
      container: true

    # My custom macro to set meta variables with the server.
    setmeta:
      name: setmeta
      container: false

    # My custom macro to set HTML backgrounds
    bg:
      name: bg
      container: false

    # My custom macro for in-passage images
    img:
      name: img
      container: false

    # Sjoerd's ported Flash macro
    # https://github.com/SjoerdHekking/custom-macros-sugarcube2
    flash:
      name: flash
      container: true

    # A custom widget to DRY
    SlotMenuInfo:
      name: SlotMenuInfo
      container: false

    # A custom widget to DRY
    SlotModMenuInfo:
      name: SlotModMenuInfo
      container: false
